version: 2.1

orbs:
  docker: circleci/docker@1.2.1
  gcp-gke: circleci/gcp-gke@1.1.0
  gcp-gcr: circleci/gcp-gcr@0.12.0

jobs:
  deploy:
    description: Deploy application to Google Kubernetes Engine
    machine: true
    parameters:
      cluster:
        description: |
          Name of gke cluster
        type: string
      container:
        description: |
          Name of docker container with organization
        type: string
      deployment:
        description: |
          Name of k8 deployment
        type: string
      image:
        description: |
          Name of docker image with organization
        type: string
      tag:
        description: |
          Docker image tag
        type: string
    steps:
      - gcp-gke/install
      - gcp-gke/update-kubeconfig-with-credentials:
          cluster: << parameters.cluster >>
          perform-login: true
      - gcp-gke/rollout-image:
          cluster: << parameters.cluster >>
          container: << parameters.container >>
          deployment: << parameters.deployment >>
          image: << parameters.image >>
          tag: << parameters.tag >>
  test:
    description: Run integration tests after deployment is finished
    docker:
      - image: circleci/golang:latest
    parameters:
      environment:
        description: |
          The environment to test
        type: string
    steps:
      - checkout
      - run: make test-<< parameters.environment >>

workflows:
  docker-build-push-deploy-dev:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: ps-chartdata
          tag: 0.0.11
          registry-url: gcr.io
          filters:
            branches:
              only:
                - dev
      - deploy:
          cluster: ps-dev
          container: ps-chartdata
          deployment: ps-chartdata
          image: gcr.io/sylvan-bonbon-317613/ps-chartdata
          tag: 0.0.11
          filters:
            branches:
              only:
                - dev
          requires:
            - gcp-gcr/build-and-push-image
  #      - test:
  #          environment: dev
  #          filters:
  #            branches:
  #              only:
  #                - dev
  #          requires:
  #            - deploy
  docker-build-push-deploy-prod:
    jobs:
      - deploy:
          cluster: ps-prod
          container: ps-chartdata
          deployment: ps-chartdata
          image: gcr.io/sylvan-bonbon-317613/ps-chartdata
          tag: 0.0.11
          filters:
            branches:
              only:
                - prod
#      - test:
#          environment: prod
#          filters:
#            branches:
#              only:
#                - prod
#          requires:
#            - deploy
