apiVersion: v1
kind: Service
metadata:
  labels:
    app: ps-chartdata
  name: ps-chartdata
spec:
  type: LoadBalancer
  ports:
    - port: 3444
      targetPort: 3444
      protocol: TCP
  selector:
    app: ps-chartdata
