apiVersion: v1
kind: Service
metadata:
  labels:
    app: ps-chartdata
  name: ps-chartdata
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: ps-chartdata
